### ISSUE TITLE
Key Error transaction_details

### ISSUE THREAD

**Issue by hofq** [gpaulissen/ofxstatement-mt940#2]
Hi, 
the Following Log i got from running your App:
![grafik](https://user-images.githubusercontent.com/54744977/170848597-6e407a5b-ad18-4487-887f-dcab956f5cb2.png)
```log
Traceback (most recent call last):                                                                                        File "C:\Python310\Scripts\ofxstatement-script.py", line 33, in <module>                                                  sys.exit(load_entry_point('ofxstatement', 'console_scripts', 'ofxstatement')())                                       File "C:\Python310\lib\site-packages\ofxstatement\tool.py", line 205, in run                                              return args.func(args)                                                                                                File "C:\Python310\lib\site-packages\ofxstatement\tool.py", line 176, in convert                                          statement = parser.parse()                                                                                            File "C:\Python310\lib\site-packages\ofxstatement\plugins\mt940.py", line 58, in parse                                    stmt: Statement = super().parse()                                                                                     File "C:\Python310\lib\site-packages\ofxstatement\parser.py", line 46, in parse                                           stmt_line = self.parse_record(line)                                                                                   File "C:\Python310\lib\site-packages\ofxstatement\plugins\mt940.py", line 118, in parse_record                            memo = transaction.data['transaction_details']                                                                      KeyError: 'transaction_details'    
````

I am Running
pip 22.0.4
Python 3.10.0 
Windows 11 22H2 Build 22000.675

My Bank is in the Part of the German Sparkasse compound, a Company by Nord/LB. I would Provide more information, but i don't know how to anonymize MT940 Data.

**Comment by s-ol** [comment]
I have the same issue with a bank from the Sparkasse compound. The file appears to use the same exact format as the `knab.sta` example.

**Comment by student-CE** [comment]
Have you found a solution please!! i have he same error shown.
